"""Pydantic v2 schemas — request/response models and internal DTOs.

Every public API surface is built from these. Consumers (frontend, eval
harness, third parties) get a stable JSON schema generated by FastAPI.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


Confidence = Literal["high", "medium", "low"]
Regulator = Literal["SEBI", "RBI"]


# ---------- request bodies ----------


class AskRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    question: str = Field(min_length=3, max_length=2000)
    top_k: int = Field(default=5, ge=1, le=20)
    regulator_filter: Regulator | None = None


class SearchRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    query: str = Field(min_length=1, max_length=2000)
    top_k: int = Field(default=10, ge=1, le=100)
    regulator_filter: Regulator | None = None
    rerank: bool = True


class IngestRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # When None we ingest all docs in the manifest. Otherwise restrict to
    # this list — useful for incremental adds or re-running a single failure.
    doc_ids: list[str] | None = None
    force: bool = False  # re-ingest even if doc already present


# ---------- internal / shared ----------


class RetrievedChunk(BaseModel):
    """A chunk returned from retrieval, with all metadata needed for citation."""

    chunk_id: str
    doc_id: str
    doc_title: str
    regulator: Regulator
    section_path: str | None = None
    page_start: int | None = None
    page_end: int | None = None
    text: str
    score: float  # post-fusion or post-rerank, depending on stage
    source_url: str

    @property
    def page(self) -> int | None:
        return self.page_start


class Citation(BaseModel):
    doc_id: str
    doc_title: str
    regulator: Regulator
    section: str | None = None
    page: int | None = None
    snippet: str
    url: str


# ---------- response bodies ----------


class AnswerResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    question: str
    answer: str
    citations: list[Citation]
    confidence: Confidence
    reasoning: str
    retrieval_method: Literal["hybrid"] = "hybrid"
    model_used: str
    tokens_used: int
    latency_ms: int
    warnings: list[str] = Field(default_factory=list)


class SearchResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    query: str
    chunks: list[RetrievedChunk]
    latency_ms: int
    retrieval_method: Literal["hybrid", "hybrid+rerank"] = "hybrid+rerank"


class IngestResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: int
    docs_processed: int
    chunks_written: int
    status: Literal["success", "partial", "failed"]
    duration_seconds: float
    errors: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    status: Literal["ok"] = "ok"
    version: str


class ReadyResponse(BaseModel):
    status: Literal["ready", "not_ready"]
    db: bool
    embedder: bool


class DocumentSummary(BaseModel):
    """Per-document overview rendered on the /documents page.

    ``preview`` is not an LLM-generated abstract — it is the first ~400
    characters of the document's first chunk that has substantial text
    (skipping any TOC-only chunks). For regulatory documents this is
    almost always the preamble or scope statement and serves as a useful
    short-paragraph summary without requiring an LLM call.
    """

    doc_id: str
    title: str
    regulator: Regulator
    category: str | None = None
    issue_date: str | None = None
    source_url: str
    num_pages: int | None = None
    chunk_count: int
    ingested_at: str | None = None
    preview: str


class DocumentsResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")

    documents: list[DocumentSummary]
    total: int
